### ISSUE TITLE
Stuck at Loading Playlist

### ISSUE THREAD

**Issue by Kilian57** [eduardolima93/playlist-manager#13]
At the moment the site dosn't work for me. It's just says "Loading playlists and songs ..." for ever. Tested on another pc.
Hope you can fix the problem. Love your work
Kilian

**Comment by fridde** [comment]
Same for me.
Any window I open the progress bar gets stuck at about 99.6%. There's probably one final issue that can't be resolved.

Also: I checked the chrome-console and I'm getting a repeated http error 429, i.e. "TOO MANY REQUESTS" returned by the API endpoint.
Maybe the request intervals could be throttled to match Spotify's rate limits?

**Comment by nl070215** [comment]
This is also happening on my end.

**Comment by K-RAD** [comment]
guess this app is no longer supported by anyone

**Comment by Sapphire44** [comment]
I've got the same problem

**Comment by KamilKot95** [comment]
same here

**Comment by webmaster0** [comment]
same here

**Comment by bardo234** [comment]
Same here.  But I hear it works for others.  Any suggestions?

**Comment by eduardolima93** [comment]
Hi guys!

I believe I fixed the issue, but I am not sure because I wasn't able to replicate the problem locally today.

Could you let me know if you're able to load the site now? It may be necessary to refresh the page with ctrl+shift+r to clean your browser's cache.

If it doesn't work, I could Zoom with one of you guys to see what is going on

**Comment by jurgh1** [comment]
> Could you let me know if you're able to load the site now? It may be necessary to refresh the page with ctrl+shift+r to clean your browser's cache.

Yes, it seems like you've fixed the issue. Thanks. Much appreciated!
