### ISSUE TITLE
tracks are not deleted 

### ISSUE THREAD

**Issue by HeMos1** [eduardolima93/playlist-manager#14]
Deleting a song from a playlist does not work for me - it stays on the list even though it has no "tick" any more. Next time I open the Playlist Manager the song is again there with the "tick" - as it is in spotify.

**Comment by TBG-FR** [comment]
It looks like it's working on my side... I just did it
Does it happen with every playlist ?

**Comment by eduardolima93** [comment]
@HeMos1 tested here and it is working for me, does this happen in all your playlists?

**Comment by HeMos1** [comment]
Thank you for checking! I just tried it again - and for some unknown reason, it now worked also for me as well! I´m sorry to have caused confusion & thanks again for looking into it!

**Comment by picnicsecurity** [comment]
I am experiencing this issue as well.  Removing songs works randomly.  Hard for me to trace down the exact issue.

**Comment by IGwonder** [comment]
The manager stays updated with the "ticks" that I have removed or added, but nothing is changing on my spotify?

**Comment by ManuDDD** [comment]
Great app ! Too bad it's working randomly. I did a few tests and this doesn't really make any sense. I had some issues in the past so I checked it was working before using it. Earlier today it was working perfectly. So I started a large playlist, only to realise once I'm done, that it wasn't working anymore. I noticed in the past it was sometime logging out without me doing anything. I was away like 2min then I was logged off. Plus there's not log out option. So I thought of a logging issue. Maybe it's still kinda logged in but it lost synch with Spotify. I tried using it with Spotify opened and closed, didn't work. I tried logging out and back in from playlist-manager just to be sure but I can't cause there no option to do so. I also thought maybe it's because I was managing playlist both in Spotify AND playlist-manager at the same time. Maybe there's some kind of conflit between the two at one point then it loses synch. Now I can't get it to work so I have no way of testing further. Maybe someone can have a look at the code with that in mind ? I'm no developper so it's just gibberish to me. Hope we can find a solution cause it's an amazing app and I think the only one out there. I use a Macbook Air with OS X 11.4 + chrome + Spotify 1.1.63.568. It was doing exactly the same on my preview set up (same + OSX 10).

**Comment by ManuDDD** [comment]
Ok now it's working....
Only thing I did is using Spotify web app instead of my desktop app.
No idea what going on but probably a synch issue between Spotify app and playlist-manager web app.
I'll post here if anything else comes up but I'd advise only using the web app. Fingers crossed.

**Comment by ManuDDD** [comment]
And it's not working again. I did literally nothing. Damn it !!!
I'm out of ideas.

**Comment by eduardolima93** [comment]
Hi guys, anyone having issues about this? I'm revisiting this project and fixing some issues.

**Comment by EricLSchurr** [comment]
I don't recall this being an issue.

Thanks for revisiting this project! Your software is fantastic!

Thanks,
Eric
________________________________

**Comment by HeMos1** [comment]
Thanks for you message - its too long ago … I can’t remind. But I’ll give it a test in the next days.

Best
helge

**Comment by eduardolima93** [comment]
Thanks, let me know if anything happens
